---
sudo: required
dist: trusty

language: c

addons:
  apt:
    packages:
    - python-docutils

before_install:
  - set -e
  - wget http://varnish-cache.org/_downloads/varnish-5.1.3.tgz
  - tar -zxf varnish-*.tar.gz
  - pushd varnish-*/
  - ./configure --prefix=/usr
  - make -sj32
  - sudo make install
  - popd

before_script:
  - ./autogen.sh
  - ./configure --prefix=/usr
  - make -j4

script:
  - make check -j4

compiler:
  - clang
  - gcc
